In [1]:
!pip install pyspark

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting pyspark
  Downloading pyspark-3.3.0.tar.gz (281.3 MB)
     |████████████████████████████████| 281.3 MB 45 kB/s
Collecting py4j==0.10.9.5
  Downloading py4j-0.10.9.5-py2.py3-none-any.whl (199 kB)
     |████████████████████████████████| 199 kB 24.3 MB/s
Building wheels for collected packages: pyspark
  Building wheel for pyspark (setup.py) ... done
  Created wheel for pyspark: filename=pyspark-3.3.0-py2.py3-none-any.whl size=281764026 sha256=83fcbf397866b2a8a9e9a042938a8d5053471c95264f570a220945bf477a22b6
  Stored in directory: /root/.cache/pip/wheels/7a/8e/1b/f73a52650d2e5f337708d9f6a1750d451a7349a867f928b885
Successfully built pyspark
Installing collected packages: py4j, pyspark
Successfully installed py4j-0.10.9.5 pyspark-3.3.0

In [2]:
import pyspark

In [3]:
#starting spark session
from pyspark.sql import SparkSession

In [4]:
spark = SparkSession.builder.appName('Practice').getOrCreate()

In [5]:
spark

In [6]:
df_pyspark = spark.read.csv('test1.csv')

In [7]:
df_pyspark.show()

+-------+----+----------+--------+
|    _c0| _c1|       _c2|     _c3|
+-------+----+----------+--------+
|   Name| age|Experience|  Salary|
| Janani|  29|         7|  100000|
|Nithin |  31|         9|10000000|
|  Sunny|  30|        10|   20000|
|   Paul|  24|         4|  398111|
| Harsha|  31|         8| 1000000|
| Varsha|  23|         2|   40000|
| Mahesh|null|      null|   29999|
|   null|  34|        10| 2888044|
|   null|  36|      null|    null|
+-------+----+----------+--------+

In [8]:
#To make header
df_pyspark = spark.read.option('header', 'true').csv('test1.csv', inferSchema=True)

In [9]:
type(df_pyspark)

pyspark.sql.dataframe.DataFrame

In [10]:
df_pyspark.head(3)

[Row(Name='Janani', age=29, Experience=7, Salary=100000),
 Row(Name='Nithin ', age=31, Experience=9, Salary=10000000),
 Row(Name='Sunny', age=30, Experience=10, Salary=20000)]

In [11]:
df_pyspark.printSchema()

root
 |-- Name: string (nullable = true)
 |-- age: integer (nullable = true)
 |-- Experience: integer (nullable = true)
 |-- Salary: integer (nullable = true)

In [12]:
df_pyspark = spark.read.csv('test1.csv', header=True, inferSchema=True)
df_pyspark.show()

+-------+----+----------+--------+
|   Name| age|Experience|  Salary|
+-------+----+----------+--------+
| Janani|  29|         7|  100000|
|Nithin |  31|         9|10000000|
|  Sunny|  30|        10|   20000|
|   Paul|  24|         4|  398111|
| Harsha|  31|         8| 1000000|
| Varsha|  23|         2|   40000|
| Mahesh|null|      null|   29999|
|   null|  34|        10| 2888044|
|   null|  36|      null|    null|
+-------+----+----------+--------+

In [13]:
df_pyspark.printSchema()

root
 |-- Name: string (nullable = true)
 |-- age: integer (nullable = true)
 |-- Experience: integer (nullable = true)
 |-- Salary: integer (nullable = true)

In [14]:
df_pyspark.columns

['Name', 'age', 'Experience', 'Salary']

In [15]:
df_pyspark.select('Name').show()

+-------+
|   Name|
+-------+
| Janani|
|Nithin |
|  Sunny|
|   Paul|
| Harsha|
| Varsha|
| Mahesh|
|   null|
|   null|
+-------+

In [16]:
df_pyspark.select(['Name', 'Experience']).show()

+-------+----------+
|   Name|Experience|
+-------+----------+
| Janani|         7|
|Nithin |         9|
|  Sunny|        10|
|   Paul|         4|
| Harsha|         8|
| Varsha|         2|
| Mahesh|      null|
|   null|        10|
|   null|      null|
+-------+----------+

In [17]:
df_pyspark.dtypes

[('Name', 'string'), ('age', 'int'), ('Experience', 'int'), ('Salary', 'int')]

In [18]:
df_pyspark.describe().show()

+-------+------+-----------------+------------------+-----------------+
|summary|  Name|              age|        Experience|           Salary|
+-------+------+-----------------+------------------+-----------------+
|  count|     7|                8|                 7|                8|
|   mean|  null|            29.75| 7.142857142857143|       1809519.25|
| stddev|  null|4.464142854857069|3.0783421635988546|3449996.089548374|
|    min|Harsha|               23|                 2|            20000|
|    max|Varsha|               36|                10|         10000000|
+-------+------+-----------------+------------------+-----------------+

In [19]:
# Adding columns in data frame
df_pyspark = df_pyspark.withColumn('Experience After 2 years', df_pyspark['Experience'] + 2)

In [20]:
df_pyspark.show()

+-------+----+----------+--------+------------------------+
|   Name| age|Experience|  Salary|Experience After 2 years|
+-------+----+----------+--------+------------------------+
| Janani|  29|         7|  100000|                       9|
|Nithin |  31|         9|10000000|                      11|
|  Sunny|  30|        10|   20000|                      12|
|   Paul|  24|         4|  398111|                       6|
| Harsha|  31|         8| 1000000|                      10|
| Varsha|  23|         2|   40000|                       4|
| Mahesh|null|      null|   29999|                    null|
|   null|  34|        10| 2888044|                      12|
|   null|  36|      null|    null|                    null|
+-------+----+----------+--------+------------------------+

In [21]:
#Drop the columns
df_pyspark = df_pyspark.drop("Experience After 2 years")

In [22]:
df_pyspark.show()

+-------+----+----------+--------+
|   Name| age|Experience|  Salary|
+-------+----+----------+--------+
| Janani|  29|         7|  100000|
|Nithin |  31|         9|10000000|
|  Sunny|  30|        10|   20000|
|   Paul|  24|         4|  398111|
| Harsha|  31|         8| 1000000|
| Varsha|  23|         2|   40000|
| Mahesh|null|      null|   29999|
|   null|  34|        10| 2888044|
|   null|  36|      null|    null|
+-------+----+----------+--------+

In [23]:
#Rename the columns
df_pyspark.withColumnRenamed('Name', 'New Name').show()

+--------+----+----------+--------+
|New Name| age|Experience|  Salary|
+--------+----+----------+--------+
|  Janani|  29|         7|  100000|
| Nithin |  31|         9|10000000|
|   Sunny|  30|        10|   20000|
|    Paul|  24|         4|  398111|
|  Harsha|  31|         8| 1000000|
|  Varsha|  23|         2|   40000|
|  Mahesh|null|      null|   29999|
|    null|  34|        10| 2888044|
|    null|  36|      null|    null|
+--------+----+----------+--------+

In [24]:
df_pyspark = spark.read.csv('test1.csv', header=True, inferSchema=True)

In [25]:
df_pyspark.show()

+-------+----+----------+--------+
|   Name| age|Experience|  Salary|
+-------+----+----------+--------+
| Janani|  29|         7|  100000|
|Nithin |  31|         9|10000000|
|  Sunny|  30|        10|   20000|
|   Paul|  24|         4|  398111|
| Harsha|  31|         8| 1000000|
| Varsha|  23|         2|   40000|
| Mahesh|null|      null|   29999|
|   null|  34|        10| 2888044|
|   null|  36|      null|    null|
+-------+----+----------+--------+

In [26]:
df_pyspark.drop('Name').show()

+----+----------+--------+
| age|Experience|  Salary|
+----+----------+--------+
|  29|         7|  100000|
|  31|         9|10000000|
|  30|        10|   20000|
|  24|         4|  398111|
|  31|         8| 1000000|
|  23|         2|   40000|
|null|      null|   29999|
|  34|        10| 2888044|
|  36|      null|    null|
+----+----------+--------+

In [27]:
#dropping null values
df_pyspark.na.drop().show()

+-------+---+----------+--------+
|   Name|age|Experience|  Salary|
+-------+---+----------+--------+
| Janani| 29|         7|  100000|
|Nithin | 31|         9|10000000|
|  Sunny| 30|        10|   20000|
|   Paul| 24|         4|  398111|
| Harsha| 31|         8| 1000000|
| Varsha| 23|         2|   40000|
+-------+---+----------+--------+

In [28]:
#all == how
#by default it is any
df_pyspark.na.drop(how ="all").show()

+-------+----+----------+--------+
|   Name| age|Experience|  Salary|
+-------+----+----------+--------+
| Janani|  29|         7|  100000|
|Nithin |  31|         9|10000000|
|  Sunny|  30|        10|   20000|
|   Paul|  24|         4|  398111|
| Harsha|  31|         8| 1000000|
| Varsha|  23|         2|   40000|
| Mahesh|null|      null|   29999|
|   null|  34|        10| 2888044|
|   null|  36|      null|    null|
+-------+----+----------+--------+

In [29]:
#Threshold - Atleast two non null values should be present
df_pyspark.na.drop(how ="any", thresh = 2).show()

+-------+----+----------+--------+
|   Name| age|Experience|  Salary|
+-------+----+----------+--------+
| Janani|  29|         7|  100000|
|Nithin |  31|         9|10000000|
|  Sunny|  30|        10|   20000|
|   Paul|  24|         4|  398111|
| Harsha|  31|         8| 1000000|
| Varsha|  23|         2|   40000|
| Mahesh|null|      null|   29999|
|   null|  34|        10| 2888044|
+-------+----+----------+--------+

In [30]:
#subset na values only from Experience column
df_pyspark.na.drop(how="any", subset=['Experience']).show()

+-------+---+----------+--------+
|   Name|age|Experience|  Salary|
+-------+---+----------+--------+
| Janani| 29|         7|  100000|
|Nithin | 31|         9|10000000|
|  Sunny| 30|        10|   20000|
|   Paul| 24|         4|  398111|
| Harsha| 31|         8| 1000000|
| Varsha| 23|         2|   40000|
|   null| 34|        10| 2888044|
+-------+---+----------+--------+

In [31]:
#Filling the missing value
df_pyspark.na.fill('Missing Values').show()

+--------------+----+----------+--------+
|          Name| age|Experience|  Salary|
+--------------+----+----------+--------+
|        Janani|  29|         7|  100000|
|       Nithin |  31|         9|10000000|
|         Sunny|  30|        10|   20000|
|          Paul|  24|         4|  398111|
|        Harsha|  31|         8| 1000000|
|        Varsha|  23|         2|   40000|
|        Mahesh|null|      null|   29999|
|Missing Values|  34|        10| 2888044|
|Missing Values|  36|      null|    null|
+--------------+----+----------+--------+

In [32]:
#Performing fill on a specific column
df_pyspark.na.fill('Missing Values', 'Experience').show()

+-------+----+----------+--------+
|   Name| age|Experience|  Salary|
+-------+----+----------+--------+
| Janani|  29|         7|  100000|
|Nithin |  31|         9|10000000|
|  Sunny|  30|        10|   20000|
|   Paul|  24|         4|  398111|
| Harsha|  31|         8| 1000000|
| Varsha|  23|         2|   40000|
| Mahesh|null|      null|   29999|
|   null|  34|        10| 2888044|
|   null|  36|      null|    null|
+-------+----+----------+--------+

In [33]:
#Performing fill on multiple columns
df_pyspark.na.fill('Missing Values', ['Experience', 'age']).show()

+-------+----+----------+--------+
|   Name| age|Experience|  Salary|
+-------+----+----------+--------+
| Janani|  29|         7|  100000|
|Nithin |  31|         9|10000000|
|  Sunny|  30|        10|   20000|
|   Paul|  24|         4|  398111|
| Harsha|  31|         8| 1000000|
| Varsha|  23|         2|   40000|
| Mahesh|null|      null|   29999|
|   null|  34|        10| 2888044|
|   null|  36|      null|    null|
+-------+----+----------+--------+

In [34]:
#Filling missing values with the mean of the column
from pyspark.ml.feature import Imputer

imputer = Imputer(
    inputCols= ['age', 'Experience', 'Salary'],
    outputCols=["{}_imputed".format(c) for c in ["age", "Experience", "Salary"]]).setStrategy("mean")

In [35]:
imputer.fit(df_pyspark).transform(df_pyspark).show()

+-------+----+----------+--------+-----------+------------------+--------------+
|   Name| age|Experience|  Salary|age_imputed|Experience_imputed|Salary_imputed|
+-------+----+----------+--------+-----------+------------------+--------------+
| Janani|  29|         7|  100000|         29|                 7|        100000|
|Nithin |  31|         9|10000000|         31|                 9|      10000000|
|  Sunny|  30|        10|   20000|         30|                10|         20000|
|   Paul|  24|         4|  398111|         24|                 4|        398111|
| Harsha|  31|         8| 1000000|         31|                 8|       1000000|
| Varsha|  23|         2|   40000|         23|                 2|         40000|
| Mahesh|null|      null|   29999|         29|                 7|         29999|
|   null|  34|        10| 2888044|         34|                10|       2888044|
|   null|  36|      null|    null|         36|                 7|       1809519|
+-------+----+----------+--------+-----------+------------------+--------------+

In [36]:
df_pyspark = spark.read.csv('test2.csv', header=True, inferSchema=True)
df_pyspark.show()

+-------+---+----------+------+
|   Name|age|Experience|Salary|
+-------+---+----------+------+
| Janani| 29|         4| 20000|
|Nithin | 31|        10| 30000|
|  Sunny| 30|         8| 25000|
|   Paul| 24|         3| 20000|
| Harsha| 21|         1| 15000|
|Shubham| 23|         2| 18000|
+-------+---+----------+------+

In [37]:
# Filter operations
# Salary <=20000
df_pyspark.filter("Salary<=20000").show()

+-------+---+----------+------+
|   Name|age|Experience|Salary|
+-------+---+----------+------+
| Janani| 29|         4| 20000|
|   Paul| 24|         3| 20000|
| Harsha| 21|         1| 15000|
|Shubham| 23|         2| 18000|
+-------+---+----------+------+

In [38]:
df_pyspark.filter("Salary<=20000").select(["Name","age"]).show()

+-------+---+
|   Name|age|
+-------+---+
| Janani| 29|
|   Paul| 24|
| Harsha| 21|
|Shubham| 23|
+-------+---+

In [39]:
#Alternative way to filter
df_pyspark.filter(df_pyspark['Salary']<=20000).show()

+-------+---+----------+------+
|   Name|age|Experience|Salary|
+-------+---+----------+------+
| Janani| 29|         4| 20000|
|   Paul| 24|         3| 20000|
| Harsha| 21|         1| 15000|
|Shubham| 23|         2| 18000|
+-------+---+----------+------+

In [40]:
#Multiple conditions
df_pyspark.filter((df_pyspark["Salary"]<=20000) & (df_pyspark["Salary"]>15000)).show()

+-------+---+----------+------+
|   Name|age|Experience|Salary|
+-------+---+----------+------+
| Janani| 29|         4| 20000|
|   Paul| 24|         3| 20000|
|Shubham| 23|         2| 18000|
+-------+---+----------+------+

In [41]:
df_pyspark.filter((df_pyspark["Salary"]<=20000) | (df_pyspark["Salary"]>15000)).show()

+-------+---+----------+------+
|   Name|age|Experience|Salary|
+-------+---+----------+------+
| Janani| 29|         4| 20000|
|Nithin | 31|        10| 30000|
|  Sunny| 30|         8| 25000|
|   Paul| 24|         3| 20000|
| Harsha| 21|         1| 15000|
|Shubham| 23|         2| 18000|
+-------+---+----------+------+

In [42]:
#not operation
df_pyspark.filter(~(df_pyspark["Salary"]<=20000)).show()

+-------+---+----------+------+
|   Name|age|Experience|Salary|
+-------+---+----------+------+
|Nithin | 31|        10| 30000|
|  Sunny| 30|         8| 25000|
+-------+---+----------+------+

In [43]:
df_pyspark = spark.read.csv('test3.csv', header = True, inferSchema=True)

In [44]:
df_pyspark.show()

+------+------------+------+
|  Name| Departments|Salary|
+------+------------+------+
|Janani|Data Science| 10000|
|Janani|         IOT|  5000|
|Mahesh|    Big Data|  4000|
|Janani|    Big Data|  4000|
|Mahesh|Data Science|  3000|
|Nithin|Data Science| 20000|
|Nithin|         IOT| 10000|
| Sunny|Data Science| 10000|
| Sunny|    Big Data|  2000|
+------+------------+------+

In [47]:
#Groupby
#Lets groupby name and retrieve the max average salary 
df_pyspark.groupBy('Name').sum().show()

+------+-----------+
|  Name|sum(Salary)|
+------+-----------+
|Janani|      19000|
| Sunny|      12000|
|Nithin|      30000|
|Mahesh|       7000|
+------+-----------+

In [48]:
#Groupby departments and retrieve the max salary
df_pyspark.groupBy('Departments').sum().show()

+------------+-----------+
| Departments|sum(Salary)|
+------------+-----------+
|         IOT|      15000|
|    Big Data|      10000|
|Data Science|      43000|
+------------+-----------+

In [49]:
df_pyspark.groupBy('Departments').mean().show()

+------------+------------------+
| Departments|       avg(Salary)|
+------------+------------------+
|         IOT|            7500.0|
|    Big Data|3333.3333333333335|
|Data Science|           10750.0|
+------------+------------------+

In [50]:
#number of employees per department
df_pyspark.groupBy('Departments').count().show()

+------------+-----+
| Departments|count|
+------------+-----+
|         IOT|    2|
|    Big Data|    3|
|Data Science|    4|
+------------+-----+

In [51]:
#Total expenditure on Salary
df_pyspark.agg({'Salary':'sum'}).show()

+-----------+
|sum(Salary)|
+-----------+
|      68000|
+-----------+

In [52]:
#Predicting salary from age and experience
training = spark.read.csv('test2.csv', header=True, inferSchema=True)

In [53]:
training.show()

+-------+---+----------+------+
|   Name|age|Experience|Salary|
+-------+---+----------+------+
| Janani| 29|         4| 20000|
|Nithin | 31|        10| 30000|
|  Sunny| 30|         8| 25000|
|   Paul| 24|         3| 20000|
| Harsha| 21|         1| 15000|
|Shubham| 23|         2| 18000|
+-------+---+----------+------+

In [54]:
training.printSchema()

root
 |-- Name: string (nullable = true)
 |-- age: integer (nullable = true)
 |-- Experience: integer (nullable = true)
 |-- Salary: integer (nullable = true)

In [55]:
training.columns

['Name', 'age', 'Experience', 'Salary']

In [56]:
from pyspark.ml.feature import VectorAssembler
featureassembler = VectorAssembler(inputCols=["age", "Experience"], outputCol="Independent Features")

In [57]:
output = featureassembler.transform(training)

In [58]:
output.show()

+-------+---+----------+------+--------------------+
|   Name|age|Experience|Salary|Independent Features|
+-------+---+----------+------+--------------------+
| Janani| 29|         4| 20000|          [29.0,4.0]|
|Nithin | 31|        10| 30000|         [31.0,10.0]|
|  Sunny| 30|         8| 25000|          [30.0,8.0]|
|   Paul| 24|         3| 20000|          [24.0,3.0]|
| Harsha| 21|         1| 15000|          [21.0,1.0]|
|Shubham| 23|         2| 18000|          [23.0,2.0]|
+-------+---+----------+------+--------------------+

In [59]:
output.columns

['Name', 'age', 'Experience', 'Salary', 'Independent Features']

In [60]:
finalized_data = output.select("Independent Features", "Salary")

In [61]:
finalized_data.show()

+--------------------+------+
|Independent Features|Salary|
+--------------------+------+
|          [29.0,4.0]| 20000|
|         [31.0,10.0]| 30000|
|          [30.0,8.0]| 25000|
|          [24.0,3.0]| 20000|
|          [21.0,1.0]| 15000|
|          [23.0,2.0]| 18000|
+--------------------+------+

In [67]:
from pyspark.ml.regression import LinearRegression
#train test split
train_data, test_data = finalized_data.randomSplit([0.75,0.25])
regressor = LinearRegression(featuresCol="Independent Features", labelCol="Salary")
regressor = regressor.fit(train_data)

In [68]:
regressor.coefficients

DenseVector([109.3058, 1199.4092])

In [69]:
regressor.intercept

12187.59231905408

In [70]:
pred_results = regressor.evaluate(test_data)

In [71]:
pred_results.predictions.show()

+--------------------+------+------------------+
|Independent Features|Salary|        prediction|
+--------------------+------+------------------+
|          [24.0,3.0]| 20000|18409.158050221544|
|         [31.0,10.0]| 30000| 27570.16248153613|
+--------------------+------+------------------+

In [72]:
pred_results.meanAbsoluteError, pred_results.meanSquaredError

(2010.339734121164, 4217444.237654793)